paths:
  CHROMA_DB_PATH: runtime/chroma_db
  CLEANED_QA_DATASET_PATH: runtime/training_generation_layer/qa_pairs_cleaned
  CLEAN_JSONL_DATA: runtime/data_cleaning/cleaned_jsonl_data
  COLLECTIONS_PATH: configs/collections.yaml
  CONVERSATION_LOGGING_PATH: runtime/logs/conversation_log.jsonl
  DEVELOPMENT_DATASET_PATH: runtime/data_layer/omnissa_dev_dataset
  DIRTY_JSONL_DATA: runtime/data_cleaning/dirty_jsonl_data
  DISTRIBUTED_DATA: configs/distributed_data.yaml
  EMA_CONFIG_PATH: configs/ema_config.yaml
  FINE_TUNE_CHECKPOINTS: runtime/fine_tuning_layer/progress_checkpoints
  FINE_TUNING: configs/fine_tuning_config.yaml
  GENERATED_QA_PATH: runtime/training_generation_layer/gen_qa_pairs_jsonl/generated_qa_pairs.jsonl
  GENERATED_QA_PATH_RAY_CLUSTER: runtime/training_generation_layer/gen_qa_pairs_jsonl/generated_qa_pairs_ray_cluster.jsonl
  INTENT_MAPPING: configs/intent_mapping.yaml
  KEY_CONTEXT_PATH: data_layer/key_context.json
  LOGGING_PATH: runtime/logs/application.log
  LOG_DIRECTORY: runtime/logs
  MODEL_FILE_READ_TOOL_FOLDER: runtime/data_layer/model_files
  NLP_CONFIG_PATH: configs/nlp_config.yaml
  OMNISSA_API_DATASET: runtime/data_layer/omnissa_api_dataset.pkl
  OMNISSA_DATASET_PATH_KB_DOC_SEED: runtime/data_layer/omnissa_static_knowledge_dataset/omnissa_kb_doc_qa_seed.jsonl
  OMNISSA_STATIC_DATASET_PATH_API: runtime/data_layer/omnissa_static_knowledge_dataset/omnissa_apis_with_context_dataset.jsonl
  OMNISSA_STATIC_DATASET_PATH_KB_DOC: runtime/data_layer/omnissa_static_knowledge_dataset/omnissa_kb_doc_dataset.jsonl
  QA_GENERATION_CONFIG: configs/qa_generation_config.yaml
  QA_GENERATION_OUTPUT_CLEANED: runtime/training_generation_layer/gen_qa_pairs_jsonl/generated_qa_pairs_cleaned.jsonl
  RAW_QA_DATASET_PATH: runtime/training_generation_layer/gen_qa_pairs_jsonl
  RAY_CLUSTER_CONFIG: configs/ray_cluster.yaml
  SAVED_MODELS_PATH: runtime/model_layer/models
  SEMANTIC_TEMPLATES_PATH: configs/semantic_templates.yaml
  SYS_THRESHOLDS: configs/system_thresholds.yaml
  WSO_DISTRIBUTED_DATA_SET_DIR: runtime/distributed_data_layer/distributed_datasets/work_space_one
  WSO_DISTRIBUTED_DIRTY_DATA_SET: runtime/distributed_data_layer/distributed_datasets/work_space_one/wso_full_cleaned_next.jsonl
  WSO_DISTRIBUTED_NODE_DATA: runtime/distributed_data_layer/distributed_cleaning/work_space_one
  WSO_TRAIN_DS: runtime/data_cleaning/wso_train_dataset
  WSO_VAL_DS: runtime/data_cleaning/wso_val_dataset
  WSO_WF_EXAMPLES: workspace_one_workflows/workflows
  WSO_WF_MAM_ENDPOINTS: workspace_one_workflows/mam
  WSO_WF_MDM_ENDPOINTS: workspace_one_workflows/mdm
  WSO_WF_SYSTEM_ENDPOINTS: workspace_one_workflows/system
